version: "1"
services:
  postgres:
    image: timescale/timescaledb:latest-pg12
    restart: always
    container_name: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=3r1qxxu9oiHs2xSRsUr8
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - ./db:/var/lib/postgresql/data/:rw
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
      interval: 10s
      timeout: 3s
      retries: 3
  frontend:
    container_name: ui
    depends_on:
      - api
    build: ./oneboard_frontend
    restart: unless-stopped
    ports:
      - "80:80"
  api:
    container_name: api
    build: ./oneboard_backend
    restart: unless-stopped
    depends_on:
      'postgres':
        condition: service_healthy
        restart: true
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - DJANGO_APP_DB_ENGINE=postgresql
      - DJANGO_APP_DB_NAME=postgres
      - DJANGO_APP_DB_USER=postgres
      - DJANGO_APP_DB_HOST=postgres
      - DJANGO_APP_DB_PORT=5432
      - DJANGO_APP_DB_PASSWORD=3r1qxxu9oiHs2xSRsUr8
    volumes:
      - ./oneboard_backend:/oneboard_backend
    command: bash -c "./entrypoint.sh"